
title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: person.maksym
      - entity: person.maryna
      - entity: sun.sun
    cards:
      - type: picture-elements
        image: /local/floorplan.png
        elements:
          - type: state-badge
            entity: sensor.mitemp_bt_temperature
            style:
              top: 50%
              left: 28%
              transform: scale(0.8)
          - type: state-badge
            entity: sensor.mitemp_bt_humidity
            style:
              top: 50%
              left: 15%
              transform: scale(0.8)
      - type: vertical-stack
        cards:
          - artwork: cover
            entity: media_player.playstation_4
            group: false
            hide:
              controls: true
              power_state: true
              source: true
              volume: true
            info: short
            source: icon
            type: 'custom:mini-media-player'
          - card:
              cards:
                - cards:
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-share'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: share
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-up'
                      show_icon: true
                      show_name: false
                      style:
                        height: 40px
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: up
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-options'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: option
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                  type: horizontal-stack
                - cards:
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-left'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: left
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-x'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: enter
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-right'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: right
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                  type: horizontal-stack
                - cards:
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: ps
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-down'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: down
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                    - aspect_ratio: 3/1
                      entity: media_player.playstation_4
                      hold_action:
                        action: more-info
                      icon: 'custom:ps4-o'
                      show_icon: true
                      show_name: false
                      tap_action:
                        action: call-service
                        service: ps4.send_command
                        service_data:
                          command: back
                          entity_id: media_player.playstation_4
                      type: 'custom:button-card'
                  type: horizontal-stack
              type: vertical-stack
            conditions:
              - entity: media_player.playstation_4
                state_not: standby
            type: conditional
      - type: media-control
        entity: media_player.living_room_tv
      - type: entities
        entities:
          - vacuum.roomba
        title: Vacuum
      - type: weather-forecast
        entity: weather.home
